#!/usr/bin/env bash
# Generated by src/scripts/generateProvisionScript.ts — do not hand-edit.
# Run in AWS CloudShell. Deletes the old bare-id-key tables (if present) and
# recreates all tables with proper partition/sort keys + GSIs.
set -euo pipefail

# --- Delete old tables (ignore errors if a table was never created / already gone) ---
aws dynamodb delete-table --table-name "AuditLog" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Category" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Conversion" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Customer" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "CustomerLedger" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Delivery" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Expense" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "InventoryTransaction" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "PasswordReset" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Payment" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Product" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Sale" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "SaleItem" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Shop" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "ShopSettings" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "Unit" >/dev/null 2>&1 || true
aws dynamodb delete-table --table-name "User" >/dev/null 2>&1 || true

# --- Wait for each delete to actually finish before recreating ---
aws dynamodb wait table-not-exists --table-name "AuditLog" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Category" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Conversion" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Customer" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "CustomerLedger" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Delivery" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Expense" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "InventoryTransaction" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "PasswordReset" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Payment" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Product" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Sale" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "SaleItem" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Shop" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "ShopSettings" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "Unit" 2>/dev/null || true
aws dynamodb wait table-not-exists --table-name "User" 2>/dev/null || true

# --- Create tables ---
echo "Creating Sale..."
aws dynamodb create-table \
  --table-name "Sale" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=code,AttributeType=S AttributeName=id,AttributeType=S AttributeName=shopCustomerKey,AttributeType=S AttributeName=shopTypeKey,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byCode","KeySchema":[{"AttributeName":"shopId","KeyType":"HASH"},{"AttributeName":"code","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byId","KeySchema":[{"AttributeName":"id","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byCustomer","KeySchema":[{"AttributeName":"shopCustomerKey","KeyType":"HASH"},{"AttributeName":"sk","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byType","KeySchema":[{"AttributeName":"shopTypeKey","KeyType":"HASH"},{"AttributeName":"sk","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating SaleCode..."
aws dynamodb create-table \
  --table-name "SaleCode" \
  --attribute-definitions AttributeName=shopCodeKey,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopCodeKey,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating SaleItem..."
aws dynamodb create-table \
  --table-name "SaleItem" \
  --attribute-definitions AttributeName=saleId,AttributeType=S AttributeName=id,AttributeType=S AttributeName=shopProductKey,AttributeType=S \
  --key-schema AttributeName=saleId,KeyType=HASH AttributeName=id,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byProduct","KeySchema":[{"AttributeName":"shopProductKey","KeyType":"HASH"},{"AttributeName":"saleId","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating Customer..."
aws dynamodb create-table \
  --table-name "Customer" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=id,AttributeType=S AttributeName=shopPhoneKey,AttributeType=S AttributeName=shopStatusKey,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=id,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byPhone","KeySchema":[{"AttributeName":"shopPhoneKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byStatus","KeySchema":[{"AttributeName":"shopStatusKey","KeyType":"HASH"},{"AttributeName":"id","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating CustomerLedger..."
aws dynamodb create-table \
  --table-name "CustomerLedger" \
  --attribute-definitions AttributeName=customerId,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=shopId,AttributeType=S AttributeName=refKey,AttributeType=S \
  --key-schema AttributeName=customerId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byShop","KeySchema":[{"AttributeName":"shopId","KeyType":"HASH"},{"AttributeName":"sk","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byRef","KeySchema":[{"AttributeName":"refKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating InventoryTransaction..."
aws dynamodb create-table \
  --table-name "InventoryTransaction" \
  --attribute-definitions AttributeName=productId,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=shopTypeKey,AttributeType=S AttributeName=refKey,AttributeType=S \
  --key-schema AttributeName=productId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byShopType","KeySchema":[{"AttributeName":"shopTypeKey","KeyType":"HASH"},{"AttributeName":"sk","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byRef","KeySchema":[{"AttributeName":"refKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating Product..."
aws dynamodb create-table \
  --table-name "Product" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=id,AttributeType=S AttributeName=shopSlugKey,AttributeType=S AttributeName=shopSkuKey,AttributeType=S AttributeName=shopCategoryKey,AttributeType=S AttributeName=shopStatusAvailKey,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=id,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"bySlug","KeySchema":[{"AttributeName":"shopSlugKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"bySku","KeySchema":[{"AttributeName":"shopSkuKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byCategory","KeySchema":[{"AttributeName":"shopCategoryKey","KeyType":"HASH"},{"AttributeName":"id","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byStatus","KeySchema":[{"AttributeName":"shopStatusAvailKey","KeyType":"HASH"},{"AttributeName":"id","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating Delivery..."
aws dynamodb create-table \
  --table-name "Delivery" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=shopStatusKey,AttributeType=S AttributeName=shopPaymentStatusKey,AttributeType=S AttributeName=shopCustomerKey,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byStatus","KeySchema":[{"AttributeName":"shopStatusKey","KeyType":"HASH"},{"AttributeName":"sk","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byPaymentStatus","KeySchema":[{"AttributeName":"shopPaymentStatusKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byCustomer","KeySchema":[{"AttributeName":"shopCustomerKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating DeliveryCode..."
aws dynamodb create-table \
  --table-name "DeliveryCode" \
  --attribute-definitions AttributeName=shopCodeKey,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopCodeKey,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating Payment..."
aws dynamodb create-table \
  --table-name "Payment" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=shopCustomerKey,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byCustomer","KeySchema":[{"AttributeName":"shopCustomerKey","KeyType":"HASH"},{"AttributeName":"sk","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating Category..."
aws dynamodb create-table \
  --table-name "Category" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=id,AttributeType=S AttributeName=shopSlugKey,AttributeType=S AttributeName=shopParentKey,AttributeType=S AttributeName=sortOrderKey,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=id,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"bySlug","KeySchema":[{"AttributeName":"shopSlugKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byParent","KeySchema":[{"AttributeName":"shopParentKey","KeyType":"HASH"},{"AttributeName":"sortOrderKey","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating Unit..."
aws dynamodb create-table \
  --table-name "Unit" \
  --attribute-definitions AttributeName=shopKey,AttributeType=S AttributeName=id,AttributeType=S AttributeName=shopSymbolKey,AttributeType=S \
  --key-schema AttributeName=shopKey,KeyType=HASH AttributeName=id,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"bySymbol","KeySchema":[{"AttributeName":"shopSymbolKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating Conversion..."
aws dynamodb create-table \
  --table-name "Conversion" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating AuditLog..."
aws dynamodb create-table \
  --table-name "AuditLog" \
  --attribute-definitions AttributeName=shopKey,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=resourceKey,AttributeType=S \
  --key-schema AttributeName=shopKey,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byResource","KeySchema":[{"AttributeName":"resourceKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating User..."
aws dynamodb create-table \
  --table-name "User" \
  --attribute-definitions AttributeName=id,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=email,AttributeType=S \
  --key-schema AttributeName=id,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byEmail","KeySchema":[{"AttributeName":"email","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating Shop..."
aws dynamodb create-table \
  --table-name "Shop" \
  --attribute-definitions AttributeName=id,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=slug,AttributeType=S AttributeName=statusDeletedKey,AttributeType=S \
  --key-schema AttributeName=id,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"bySlug","KeySchema":[{"AttributeName":"slug","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}},{"IndexName":"byStatus","KeySchema":[{"AttributeName":"statusDeletedKey","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating ShopOwnerGuard..."
aws dynamodb create-table \
  --table-name "ShopOwnerGuard" \
  --attribute-definitions AttributeName=ownerId,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=ownerId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating ShopSettings..."
aws dynamodb create-table \
  --table-name "ShopSettings" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating PasswordReset..."
aws dynamodb create-table \
  --table-name "PasswordReset" \
  --attribute-definitions AttributeName=email,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=email,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating Expense..."
aws dynamodb create-table \
  --table-name "Expense" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=sk,AttributeType=S AttributeName=shopCategoryKey,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"byCategory","KeySchema":[{"AttributeName":"shopCategoryKey","KeyType":"HASH"},{"AttributeName":"sk","KeyType":"RANGE"}],"Projection":{"ProjectionType":"ALL"}}]'

echo "Creating DailyShopSummary..."
aws dynamodb create-table \
  --table-name "DailyShopSummary" \
  --attribute-definitions AttributeName=shopId,AttributeType=S AttributeName=date,AttributeType=S \
  --key-schema AttributeName=shopId,KeyType=HASH AttributeName=date,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating ProductSlugGuard..."
aws dynamodb create-table \
  --table-name "ProductSlugGuard" \
  --attribute-definitions AttributeName=shopSlugKey,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopSlugKey,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating ProductSkuGuard..."
aws dynamodb create-table \
  --table-name "ProductSkuGuard" \
  --attribute-definitions AttributeName=shopSkuKey,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopSkuKey,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating CategorySlugGuard..."
aws dynamodb create-table \
  --table-name "CategorySlugGuard" \
  --attribute-definitions AttributeName=shopSlugKey,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopSlugKey,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating UnitSymbolGuard..."
aws dynamodb create-table \
  --table-name "UnitSymbolGuard" \
  --attribute-definitions AttributeName=shopSymbolKey,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=shopSymbolKey,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating ShopSlugGuard..."
aws dynamodb create-table \
  --table-name "ShopSlugGuard" \
  --attribute-definitions AttributeName=slug,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=slug,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Creating UserEmailGuard..."
aws dynamodb create-table \
  --table-name "UserEmailGuard" \
  --attribute-definitions AttributeName=email,AttributeType=S AttributeName=sk,AttributeType=S \
  --key-schema AttributeName=email,KeyType=HASH AttributeName=sk,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST

echo "Waiting for all tables to become ACTIVE..."
aws dynamodb wait table-exists --table-name "Sale"
aws dynamodb wait table-exists --table-name "SaleCode"
aws dynamodb wait table-exists --table-name "SaleItem"
aws dynamodb wait table-exists --table-name "Customer"
aws dynamodb wait table-exists --table-name "CustomerLedger"
aws dynamodb wait table-exists --table-name "InventoryTransaction"
aws dynamodb wait table-exists --table-name "Product"
aws dynamodb wait table-exists --table-name "Delivery"
aws dynamodb wait table-exists --table-name "DeliveryCode"
aws dynamodb wait table-exists --table-name "Payment"
aws dynamodb wait table-exists --table-name "Category"
aws dynamodb wait table-exists --table-name "Unit"
aws dynamodb wait table-exists --table-name "Conversion"
aws dynamodb wait table-exists --table-name "AuditLog"
aws dynamodb wait table-exists --table-name "User"
aws dynamodb wait table-exists --table-name "Shop"
aws dynamodb wait table-exists --table-name "ShopOwnerGuard"
aws dynamodb wait table-exists --table-name "ShopSettings"
aws dynamodb wait table-exists --table-name "PasswordReset"
aws dynamodb wait table-exists --table-name "Expense"
aws dynamodb wait table-exists --table-name "DailyShopSummary"
aws dynamodb wait table-exists --table-name "ProductSlugGuard"
aws dynamodb wait table-exists --table-name "ProductSkuGuard"
aws dynamodb wait table-exists --table-name "CategorySlugGuard"
aws dynamodb wait table-exists --table-name "UnitSymbolGuard"
aws dynamodb wait table-exists --table-name "ShopSlugGuard"
aws dynamodb wait table-exists --table-name "UserEmailGuard"

# --- Enable TTL where defined ---
aws dynamodb update-time-to-live --table-name "PasswordReset" --time-to-live-specification "Enabled=true,AttributeName=ttl"

echo "Done. Verify with: aws dynamodb list-tables --output table"
