import { TABLE_DEFS, tableName, type TableDef } from '../config/dynamoTables.js';

/**
 * Emits an AWS CLI bash script (to stdout) that deletes the old bare-`id`-key
 * tables and recreates all tables from TABLE_DEFS with proper keys/GSIs.
 * Generated (not hand-written) so the CloudShell script can never drift from
 * the TypeScript source of truth. Run: `npx tsx src/scripts/generateProvisionScript.ts > provision-dynamodb.sh`
 * then paste that file's contents into AWS CloudShell.
 */

function attrDefs(t: TableDef): string {
  const attrs = new Map<string, string>();
  attrs.set(t.pk.name, t.pk.type);
  if (t.sk) attrs.set(t.sk.name, t.sk.type);
  for (const g of t.gsis ?? []) {
    attrs.set(g.pk.name, g.pk.type);
    if (g.sk) attrs.set(g.sk.name, g.sk.type);
  }
  return [...attrs.entries()].map(([n, ty]) => `AttributeName=${n},AttributeType=${ty}`).join(' ');
}

function keySchema(pk: { name: string }, sk?: { name: string }): string {
  const parts = [`AttributeName=${pk.name},KeyType=HASH`];
  if (sk) parts.push(`AttributeName=${sk.name},KeyType=RANGE`);
  return parts.join(' ');
}

function gsiJson(t: TableDef): string | null {
  if (!t.gsis?.length) return null;
  const defs = t.gsis.map((g) => ({
    IndexName: g.name,
    KeySchema: [
      { AttributeName: g.pk.name, KeyType: 'HASH' },
      ...(g.sk ? [{ AttributeName: g.sk.name, KeyType: 'RANGE' }] : []),
    ],
    Projection: { ProjectionType: g.projection ?? 'ALL' },
  }));
  return JSON.stringify(defs);
}

const lines: string[] = [
  '#!/usr/bin/env bash',
  '# Generated by src/scripts/generateProvisionScript.ts — do not hand-edit.',
  '# Run in AWS CloudShell. Deletes the old bare-id-key tables (if present) and',
  '# recreates all tables with proper partition/sort keys + GSIs.',
  'set -euo pipefail',
  '',
  '# --- Delete old tables (ignore errors if a table was never created / already gone) ---',
];

const OLD_17 = [
  'AuditLog', 'Category', 'Conversion', 'Customer', 'CustomerLedger', 'Delivery', 'Expense',
  'InventoryTransaction', 'PasswordReset', 'Payment', 'Product', 'Sale', 'SaleItem', 'Shop',
  'ShopSettings', 'Unit', 'User',
];
for (const t of OLD_17) {
  lines.push(`aws dynamodb delete-table --table-name "${t}" >/dev/null 2>&1 || true`);
}
lines.push('', '# --- Wait for each delete to actually finish before recreating ---');
for (const t of OLD_17) {
  lines.push(`aws dynamodb wait table-not-exists --table-name "${t}" 2>/dev/null || true`);
}
lines.push('', '# --- Create tables ---');

for (const t of TABLE_DEFS) {
  const name = tableName(t.logicalName);
  lines.push(`echo "Creating ${name}..."`);
  let cmd = `aws dynamodb create-table \\\n  --table-name "${name}" \\\n  --attribute-definitions ${attrDefs(t)} \\\n  --key-schema ${keySchema(t.pk, t.sk)} \\\n  --billing-mode PAY_PER_REQUEST`;
  const gsi = gsiJson(t);
  if (gsi) cmd += ` \\\n  --global-secondary-indexes '${gsi}'`;
  lines.push(cmd);
  lines.push('');
}

lines.push('echo "Waiting for all tables to become ACTIVE..."');
for (const t of TABLE_DEFS) {
  lines.push(`aws dynamodb wait table-exists --table-name "${tableName(t.logicalName)}"`);
}
lines.push('');

lines.push('# --- Enable TTL where defined ---');
for (const t of TABLE_DEFS) {
  if (!t.ttlAttribute) continue;
  lines.push(
    `aws dynamodb update-time-to-live --table-name "${tableName(t.logicalName)}" ` +
      `--time-to-live-specification "Enabled=true,AttributeName=${t.ttlAttribute}"`,
  );
}
lines.push('', 'echo "Done. Verify with: aws dynamodb list-tables --output table"');

// eslint-disable-next-line no-console
console.log(lines.join('\n'));
