import { Role } from './roles.js';

/** Granular permission keys (§31). Add here; wire into role defaults below. */
export const Permission = {
  SHOP_VIEW: 'SHOP_VIEW',
  SHOP_UPDATE: 'SHOP_UPDATE',
  SHOP_CREATE: 'SHOP_CREATE',
  SHOP_DELETE: 'SHOP_DELETE',
  SHOP_APPROVE: 'SHOP_APPROVE',
  SHOP_SUSPEND: 'SHOP_SUSPEND',

  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  UNIT_MANAGE: 'UNIT_MANAGE',

  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',

  SALE_VIEW: 'SALE_VIEW',
  SALE_CREATE: 'SALE_CREATE',
  SALE_REVERSE: 'SALE_REVERSE',

  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',

  LEDGER_VIEW: 'LEDGER_VIEW',

  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_REVERSE: 'PAYMENT_REVERSE',

  DELIVERY_VIEW: 'DELIVERY_VIEW',
  DELIVERY_MANAGE: 'DELIVERY_MANAGE',

  EXPENSE_VIEW: 'EXPENSE_VIEW',
  EXPENSE_CREATE: 'EXPENSE_CREATE',

  REPORT_VIEW: 'REPORT_VIEW',

  SETTINGS_VIEW: 'SETTINGS_VIEW',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',

  USER_MANAGE: 'USER_MANAGE',

  PLATFORM_MANAGE: 'PLATFORM_MANAGE',
  AUDIT_VIEW: 'AUDIT_VIEW',
  IMPERSONATE_SHOP: 'IMPERSONATE_SHOP',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

const P = Permission;

const SHOP_ADMIN_PERMS: Permission[] = [
  P.SHOP_VIEW, P.SHOP_UPDATE,
  P.CATEGORY_VIEW, P.CATEGORY_CREATE, P.CATEGORY_UPDATE, P.CATEGORY_DELETE,
  P.PRODUCT_VIEW, P.PRODUCT_CREATE, P.PRODUCT_UPDATE, P.PRODUCT_DELETE,
  P.UNIT_MANAGE,
  P.INVENTORY_VIEW, P.INVENTORY_ADJUST,
  P.SALE_VIEW, P.SALE_CREATE, P.SALE_REVERSE,
  P.CUSTOMER_VIEW, P.CUSTOMER_CREATE, P.CUSTOMER_UPDATE, P.CUSTOMER_DELETE,
  P.LEDGER_VIEW,
  P.PAYMENT_VIEW, P.PAYMENT_CREATE, P.PAYMENT_REVERSE,
  P.DELIVERY_VIEW, P.DELIVERY_MANAGE,
  P.EXPENSE_VIEW, P.EXPENSE_CREATE,
  P.REPORT_VIEW,
  P.SETTINGS_VIEW, P.SETTINGS_UPDATE,
  P.USER_MANAGE,
];

const SHOP_STAFF_PERMS: Permission[] = [
  P.SHOP_VIEW,
  P.CATEGORY_VIEW,
  P.PRODUCT_VIEW,
  P.INVENTORY_VIEW, P.INVENTORY_ADJUST,
  P.SALE_VIEW, P.SALE_CREATE,
  P.CUSTOMER_VIEW, P.CUSTOMER_CREATE, P.CUSTOMER_UPDATE,
  P.LEDGER_VIEW,
  P.PAYMENT_VIEW, P.PAYMENT_CREATE,
  P.DELIVERY_VIEW, P.DELIVERY_MANAGE,
  P.REPORT_VIEW,
];

/** SUPER_ADMIN implicitly holds every permission (checked in authorize()). */
export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Object.values(P),
  [Role.SHOP_ADMIN]: SHOP_ADMIN_PERMS,
  [Role.SHOP_STAFF]: SHOP_STAFF_PERMS,
  [Role.USER]: [],
};

export function defaultPermissionsFor(role: Role): Permission[] {
  return DEFAULT_ROLE_PERMISSIONS[role] ?? [];
}
